### ISSUE TITLE
throw event error

### ISSUE THREAD

**Issue by xiaomingming** [gratimax/gulp-grunt#26]
It's my gulp config:
```
var gulp = require('gulp');
require('gulp-grunt')(gulp,{
    base: './',
    prefix: 'grunt-',
    verbose: false
});
gulp.task('tpl', function() {
    return gulp.start('grunt-tpl');
});
```
when i execute `gulp tpl`,my console throw event error:
```
$ gulp tpl
[18:36:26] Using gulpfile f:\A_local\vipMobile\gulpfile.js
[18:36:26] Starting 'tpl'...
[18:36:26] Starting 'grunt-tpl'...
[18:36:26] Finished 'tpl' after 4.99 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn .//grunt.cmd ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3
```
what's wrong with me?

**Comment by xiaomingming** [comment]
Well,`base`  set  `null`.
